// Source: U.S. Census Bureau, Annual Estimates of the Resident Population for Incorporated Places in the United States: April 1, 2020 to July 1, 2024.
// Downloaded from https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/cities/totals/sub-est2024.csv during CP22A.1 implementation.
// This bounded subset keeps the top 900 places nationally plus each state/DC top five where available.
// City names are ASCII-folded and legal place suffixes are stripped for stable Google Maps market queries.

export type UsSweepCity = {
  city: string
  stateId: string
  stateName: string
  population: number
}

export const US_SWEEP_CITY_DATASET = {
  source: 'U.S. Census Bureau sub-est2024.csv',
  sourceUrl: 'https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/cities/totals/sub-est2024.csv',
  sourceLicense: 'U.S. federal government public data',
  rowCount: 934,
  coverage: '50 states plus District of Columbia',
} as const

export const US_SWEEP_CITIES: UsSweepCity[] = [
  { city: 'New York', stateId: 'NY', stateName: 'New York', population: 8478072 },
  { city: 'Los Angeles', stateId: 'CA', stateName: 'California', population: 3878704 },
  { city: 'Chicago', stateId: 'IL', stateName: 'Illinois', population: 2721308 },
  { city: 'Houston', stateId: 'TX', stateName: 'Texas', population: 2390125 },
  { city: 'Phoenix', stateId: 'AZ', stateName: 'Arizona', population: 1673164 },
  { city: 'Philadelphia', stateId: 'PA', stateName: 'Pennsylvania', population: 1573916 },
  { city: 'San Antonio', stateId: 'TX', stateName: 'Texas', population: 1526656 },
  { city: 'San Diego', stateId: 'CA', stateName: 'California', population: 1404452 },
  { city: 'Dallas', stateId: 'TX', stateName: 'Texas', population: 1326087 },
  { city: 'Jacksonville', stateId: 'FL', stateName: 'Florida', population: 1009833 },
  { city: 'Fort Worth', stateId: 'TX', stateName: 'Texas', population: 1008106 },
  { city: 'San Jose', stateId: 'CA', stateName: 'California', population: 997368 },
  { city: 'Austin', stateId: 'TX', stateName: 'Texas', population: 993588 },
  { city: 'Charlotte', stateId: 'NC', stateName: 'North Carolina', population: 943476 },
  { city: 'Columbus', stateId: 'OH', stateName: 'Ohio', population: 933263 },
  { city: 'Indianapolis', stateId: 'IN', stateName: 'Indiana', population: 891484 },
  { city: 'San Francisco', stateId: 'CA', stateName: 'California', population: 827526 },
  { city: 'Seattle', stateId: 'WA', stateName: 'Washington', population: 780995 },
  { city: 'Denver', stateId: 'CO', stateName: 'Colorado', population: 729019 },
  { city: 'Oklahoma City', stateId: 'OK', stateName: 'Oklahoma', population: 712919 },
  { city: 'Nashville', stateId: 'TN', stateName: 'Tennessee', population: 704963 },
  { city: 'Washington', stateId: 'DC', stateName: 'District of Columbia', population: 702250 },
  { city: 'El Paso', stateId: 'TX', stateName: 'Texas', population: 681723 },
  { city: 'Las Vegas', stateId: 'NV', stateName: 'Nevada', population: 678922 },
  { city: 'Boston', stateId: 'MA', stateName: 'Massachusetts', population: 673458 },
  { city: 'Detroit', stateId: 'MI', stateName: 'Michigan', population: 645705 },
  { city: 'Louisville', stateId: 'KY', stateName: 'Kentucky', population: 640796 },
  { city: 'Portland', stateId: 'OR', stateName: 'Oregon', population: 635749 },
  { city: 'Memphis', stateId: 'TN', stateName: 'Tennessee', population: 610919 },
  { city: 'Baltimore', stateId: 'MD', stateName: 'Maryland', population: 568271 },
  { city: 'Milwaukee', stateId: 'WI', stateName: 'Wisconsin', population: 563531 },
  { city: 'Albuquerque', stateId: 'NM', stateName: 'New Mexico', population: 560326 },
  { city: 'Tucson', stateId: 'AZ', stateName: 'Arizona', population: 554013 },
  { city: 'Fresno', stateId: 'CA', stateName: 'California', population: 550105 },
  { city: 'Sacramento', stateId: 'CA', stateName: 'California', population: 535798 },
  { city: 'Atlanta', stateId: 'GA', stateName: 'Georgia', population: 520070 },
  { city: 'Mesa', stateId: 'AZ', stateName: 'Arizona', population: 517151 },
  { city: 'Kansas City', stateId: 'MO', stateName: 'Missouri', population: 516032 },
  { city: 'Raleigh', stateId: 'NC', stateName: 'North Carolina', population: 499825 },
  { city: 'Colorado Springs', stateId: 'CO', stateName: 'Colorado', population: 493554 },
  { city: 'Omaha', stateId: 'NE', stateName: 'Nebraska', population: 489265 },
  { city: 'Miami', stateId: 'FL', stateName: 'Florida', population: 487014 },
  { city: 'Virginia Beach', stateId: 'VA', stateName: 'Virginia', population: 454808 },
  { city: 'Long Beach', stateId: 'CA', stateName: 'California', population: 450901 },
  { city: 'Oakland', stateId: 'CA', stateName: 'California', population: 443554 },
  { city: 'Minneapolis', stateId: 'MN', stateName: 'Minnesota', population: 428579 },
  { city: 'Bakersfield', stateId: 'CA', stateName: 'California', population: 417468 },
  { city: 'Tulsa', stateId: 'OK', stateName: 'Oklahoma', population: 415154 },
  { city: 'Tampa', stateId: 'FL', stateName: 'Florida', population: 414547 },
  { city: 'Arlington', stateId: 'TX', stateName: 'Texas', population: 403672 },
  { city: 'Aurora', stateId: 'CO', stateName: 'Colorado', population: 403130 },
  { city: 'Wichita', stateId: 'KS', stateName: 'Kansas', population: 400991 },
  { city: 'Cleveland', stateId: 'OH', stateName: 'Ohio', population: 365379 },
  { city: 'New Orleans', stateId: 'LA', stateName: 'Louisiana', population: 362701 },
  { city: 'Henderson', stateId: 'NV', stateName: 'Nevada', population: 350039 },
  { city: 'Urban Honolulu', stateId: 'HI', stateName: 'Hawaii', population: 344967 },
  { city: 'Anaheim', stateId: 'CA', stateName: 'California', population: 344561 },
  { city: 'Orlando', stateId: 'FL', stateName: 'Florida', population: 334854 },
  { city: 'Lexington', stateId: 'KY', stateName: 'Kentucky', population: 329437 },
  { city: 'Stockton', stateId: 'CA', stateName: 'California', population: 324975 },
  { city: 'Riverside', stateId: 'CA', stateName: 'California', population: 323757 },
  { city: 'Irvine', stateId: 'CA', stateName: 'California', population: 318683 },
  { city: 'Corpus Christi', stateId: 'TX', stateName: 'Texas', population: 317317 },
  { city: 'Newark', stateId: 'NJ', stateName: 'New Jersey', population: 317303 },
  { city: 'Santa Ana', stateId: 'CA', stateName: 'California', population: 316184 },
  { city: 'Cincinnati', stateId: 'OH', stateName: 'Ohio', population: 314915 },
  { city: 'Pittsburgh', stateId: 'PA', stateName: 'Pennsylvania', population: 307668 },
  { city: 'St. Paul', stateId: 'MN', stateName: 'Minnesota', population: 307465 },
  { city: 'Greensboro', stateId: 'NC', stateName: 'North Carolina', population: 307381 },
  { city: 'Jersey City', stateId: 'NJ', stateName: 'New Jersey', population: 302824 },
  { city: 'Durham', stateId: 'NC', stateName: 'North Carolina', population: 301870 },
  { city: 'Lincoln', stateId: 'NE', stateName: 'Nebraska', population: 300619 },
  { city: 'North Las Vegas', stateId: 'NV', stateName: 'Nevada', population: 294034 },
  { city: 'Plano', stateId: 'TX', stateName: 'Texas', population: 293286 },
  { city: 'Anchorage', stateId: 'AK', stateName: 'Alaska', population: 289600 },
  { city: 'Gilbert', stateId: 'AZ', stateName: 'Arizona', population: 288790 },
  { city: 'Madison', stateId: 'WI', stateName: 'Wisconsin', population: 285300 },
  { city: 'Reno', stateId: 'NV', stateName: 'Nevada', population: 281714 },
  { city: 'Chandler', stateId: 'AZ', stateName: 'Arizona', population: 281231 },
  { city: 'St. Louis', stateId: 'MO', stateName: 'Missouri', population: 279695 },
  { city: 'Chula Vista', stateId: 'CA', stateName: 'California', population: 278546 },
  { city: 'Buffalo', stateId: 'NY', stateName: 'New York', population: 276617 },
  { city: 'Fort Wayne', stateId: 'IN', stateName: 'Indiana', population: 273203 },
  { city: 'Lubbock', stateId: 'TX', stateName: 'Texas', population: 272086 },
  { city: 'St. Petersburg', stateId: 'FL', stateName: 'Florida', population: 267102 },
  { city: 'Toledo', stateId: 'OH', stateName: 'Ohio', population: 265638 },
  { city: 'Laredo', stateId: 'TX', stateName: 'Texas', population: 261260 },
  { city: 'Port St. Lucie', stateId: 'FL', stateName: 'Florida', population: 258575 },
  { city: 'Glendale', stateId: 'AZ', stateName: 'Arizona', population: 258143 },
  { city: 'Irving', stateId: 'TX', stateName: 'Texas', population: 258060 },
  { city: 'Winston-Salem', stateId: 'NC', stateName: 'North Carolina', population: 255769 },
  { city: 'Chesapeake', stateId: 'VA', stateName: 'Virginia', population: 254997 },
  { city: 'Garland', stateId: 'TX', stateName: 'Texas', population: 250431 },
  { city: 'Scottsdale', stateId: 'AZ', stateName: 'Arizona', population: 246170 },
  { city: 'Boise City', stateId: 'ID', stateName: 'Idaho', population: 237963 },
  { city: 'Hialeah', stateId: 'FL', stateName: 'Florida', population: 235388 },
  { city: 'Frisco', stateId: 'TX', stateName: 'Texas', population: 235208 },
  { city: 'Richmond', stateId: 'VA', stateName: 'Virginia', population: 233655 },
  { city: 'Cape Coral', stateId: 'FL', stateName: 'Florida', population: 233025 },
  { city: 'Norfolk', stateId: 'VA', stateName: 'Virginia', population: 231105 },
  { city: 'Spokane', stateId: 'WA', stateName: 'Washington', population: 230609 },
  { city: 'Huntsville', stateId: 'AL', stateName: 'Alabama', population: 230402 },
  { city: 'Santa Clarita', stateId: 'CA', stateName: 'California', population: 229159 },
  { city: 'Tacoma', stateId: 'WA', stateName: 'Washington', population: 228202 },
  { city: 'Fremont', stateId: 'CA', stateName: 'California', population: 228192 },
  { city: 'McKinney', stateId: 'TX', stateName: 'Texas', population: 227526 },
  { city: 'San Bernardino', stateId: 'CA', stateName: 'California', population: 224775 },
  { city: 'Baton Rouge', stateId: 'LA', stateName: 'Louisiana', population: 220907 },
  { city: 'Modesto', stateId: 'CA', stateName: 'California', population: 220592 },
  { city: 'Fontana', stateId: 'CA', stateName: 'California', population: 218455 },
  { city: 'Salt Lake City', stateId: 'UT', stateName: 'Utah', population: 217783 },
  { city: 'Moreno Valley', stateId: 'CA', stateName: 'California', population: 213919 },
  { city: 'Des Moines', stateId: 'IA', stateName: 'Iowa', population: 213096 },
  { city: 'Worcester', stateId: 'MA', stateName: 'Massachusetts', population: 211286 },
  { city: 'Yonkers', stateId: 'NY', stateName: 'New York', population: 211040 },
  { city: 'Fayetteville', stateId: 'NC', stateName: 'North Carolina', population: 209496 },
  { city: 'Sioux Falls', stateId: 'SD', stateName: 'South Dakota', population: 209289 },
  { city: 'Grand Prairie', stateId: 'TX', stateName: 'Texas', population: 207331 },
  { city: 'Rochester', stateId: 'NY', stateName: 'New York', population: 207282 },
  { city: 'Tallahassee', stateId: 'FL', stateName: 'Florida', population: 205089 },
  { city: 'Little Rock', stateId: 'AR', stateName: 'Arkansas', population: 204774 },
  { city: 'Amarillo', stateId: 'TX', stateName: 'Texas', population: 203729 },
  { city: 'Overland Park', stateId: 'KS', stateName: 'Kansas', population: 202893 },
  { city: 'Columbus', stateId: 'GA', stateName: 'Georgia', population: 201830 },
  { city: 'Augusta', stateId: 'GA', stateName: 'Georgia', population: 201737 },
  { city: 'Mobile', stateId: 'AL', stateName: 'Alabama', population: 201367 },
  { city: 'Oxnard', stateId: 'CA', stateName: 'California', population: 200616 },
  { city: 'Grand Rapids', stateId: 'MI', stateName: 'Michigan', population: 200117 },
  { city: 'Peoria', stateId: 'AZ', stateName: 'Arizona', population: 199924 },
  { city: 'Vancouver', stateId: 'WA', stateName: 'Washington', population: 198992 },
  { city: 'Knoxville', stateId: 'TN', stateName: 'Tennessee', population: 198722 },
  { city: 'Birmingham', stateId: 'AL', stateName: 'Alabama', population: 196357 },
  { city: 'Montgomery', stateId: 'AL', stateName: 'Alabama', population: 195818 },
  { city: 'Providence', stateId: 'RI', stateName: 'Rhode Island', population: 194706 },
  { city: 'Huntington Beach', stateId: 'CA', stateName: 'California', population: 193151 },
  { city: 'Brownsville', stateId: 'TX', stateName: 'Texas', population: 191967 },
  { city: 'Chattanooga', stateId: 'TN', stateName: 'Tennessee', population: 191496 },
  { city: 'Fort Lauderdale', stateId: 'FL', stateName: 'Florida', population: 190641 },
  { city: 'Tempe', stateId: 'AZ', stateName: 'Arizona', population: 190114 },
  { city: 'Akron', stateId: 'OH', stateName: 'Ohio', population: 189664 },
  { city: 'Glendale', stateId: 'CA', stateName: 'California', population: 187823 },
  { city: 'Clarksville', stateId: 'TN', stateName: 'Tennessee', population: 185690 },
  { city: 'Ontario', stateId: 'CA', stateName: 'California', population: 185285 },
  { city: 'Newport News', stateId: 'VA', stateName: 'Virginia', population: 183056 },
  { city: 'Elk Grove', stateId: 'CA', stateName: 'California', population: 182797 },
  { city: 'Cary', stateId: 'NC', stateName: 'North Carolina', population: 182659 },
  { city: 'Aurora', stateId: 'IL', stateName: 'Illinois', population: 180710 },
  { city: 'Salem', stateId: 'OR', stateName: 'Oregon', population: 180406 },
  { city: 'Pembroke Pines', stateId: 'FL', stateName: 'Florida', population: 179326 },
  { city: 'Eugene', stateId: 'OR', stateName: 'Oregon', population: 178786 },
  { city: 'Santa Rosa', stateId: 'CA', stateName: 'California', population: 177524 },
  { city: 'Rancho Cucamonga', stateId: 'CA', stateName: 'California', population: 176675 },
  { city: 'Shreveport', stateId: 'LA', stateName: 'Louisiana', population: 176578 },
  { city: 'Garden Grove', stateId: 'CA', stateName: 'California', population: 172361 },
  { city: 'Oceanside', stateId: 'CA', stateName: 'California', population: 170941 },
  { city: 'Fort Collins', stateId: 'CO', stateName: 'Colorado', population: 170924 },
  { city: 'Springfield', stateId: 'MO', stateName: 'Missouri', population: 170596 },
  { city: 'Murfreesboro', stateId: 'TN', stateName: 'Tennessee', population: 168387 },
  { city: 'Surprise', stateId: 'AZ', stateName: 'Arizona', population: 167564 },
  { city: 'Lancaster', stateId: 'CA', stateName: 'California', population: 167426 },
  { city: 'Denton', stateId: 'TX', stateName: 'Texas', population: 165998 },
  { city: 'Roseville', stateId: 'CA', stateName: 'California', population: 163304 },
  { city: 'Palmdale', stateId: 'CA', stateName: 'California', population: 162536 },
  { city: 'Corona', stateId: 'CA', stateName: 'California', population: 161540 },
  { city: 'Salinas', stateId: 'CA', stateName: 'California', population: 160783 },
  { city: 'Killeen', stateId: 'TX', stateName: 'Texas', population: 160616 },
  { city: 'Paterson', stateId: 'NJ', stateName: 'New Jersey', population: 160463 },
  { city: 'Alexandria', stateId: 'VA', stateName: 'Virginia', population: 159102 },
  { city: 'Hollywood', stateId: 'FL', stateName: 'Florida', population: 159073 },
  { city: 'Hayward', stateId: 'CA', stateName: 'California', population: 158440 },
  { city: 'Charleston', stateId: 'SC', stateName: 'South Carolina', population: 157665 },
  { city: 'Macon', stateId: 'GA', stateName: 'Georgia', population: 157056 },
  { city: 'Lakewood', stateId: 'CO', stateName: 'Colorado', population: 156868 },
  { city: 'Sunnyvale', stateId: 'CA', stateName: 'California', population: 156792 },
  { city: 'Kansas City', stateId: 'KS', stateName: 'Kansas', population: 156752 },
  { city: 'Springfield', stateId: 'MA', stateName: 'Massachusetts', population: 154888 },
  { city: 'Bellevue', stateId: 'WA', stateName: 'Washington', population: 154377 },
  { city: 'Naperville', stateId: 'IL', stateName: 'Illinois', population: 153124 },
  { city: 'Joliet', stateId: 'IL', stateName: 'Illinois', population: 151837 },
  { city: 'Bridgeport', stateId: 'CT', stateName: 'Connecticut', population: 151599 },
  { city: 'Mesquite', stateId: 'TX', stateName: 'Texas', population: 150140 },
  { city: 'Pasadena', stateId: 'TX', stateName: 'Texas', population: 149617 },
  { city: 'Olathe', stateId: 'KS', stateName: 'Kansas', population: 149035 },
  { city: 'Escondido', stateId: 'CA', stateName: 'California', population: 148847 },
  { city: 'Savannah', stateId: 'GA', stateName: 'Georgia', population: 148808 },
  { city: 'McAllen', stateId: 'TX', stateName: 'Texas', population: 148782 },
  { city: 'Gainesville', stateId: 'FL', stateName: 'Florida', population: 148720 },
  { city: 'Pomona', stateId: 'CA', stateName: 'California', population: 147966 },
  { city: 'Rockford', stateId: 'IL', stateName: 'Illinois', population: 147486 },
  { city: 'Thornton', stateId: 'CO', stateName: 'Colorado', population: 146689 },
  { city: 'Waco', stateId: 'TX', stateName: 'Texas', population: 146608 },
  { city: 'Visalia', stateId: 'CA', stateName: 'California', population: 146271 },
  { city: 'Syracuse', stateId: 'NY', stateName: 'New York', population: 146097 },
  { city: 'Columbia', stateId: 'SC', stateName: 'South Carolina', population: 144788 },
  { city: 'Midland', stateId: 'TX', stateName: 'Texas', population: 143687 },
  { city: 'Miramar', stateId: 'FL', stateName: 'Florida', population: 143242 },
  { city: 'Palm Bay', stateId: 'FL', stateName: 'Florida', population: 142023 },
  { city: 'Jackson', stateId: 'MS', stateName: 'Mississippi', population: 141449 },
  { city: 'Coral Springs', stateId: 'FL', stateName: 'Florida', population: 140808 },
  { city: 'Victorville', stateId: 'CA', stateName: 'California', population: 140721 },
  { city: 'Elizabeth', stateId: 'NJ', stateName: 'New Jersey', population: 140413 },
  { city: 'Fullerton', stateId: 'CA', stateName: 'California', population: 140054 },
  { city: 'Meridian', stateId: 'ID', stateName: 'Idaho', population: 139740 },
  { city: 'Torrance', stateId: 'CA', stateName: 'California', population: 139576 },
  { city: 'Stamford', stateId: 'CT', stateName: 'Connecticut', population: 139134 },
  { city: 'West Valley City', stateId: 'UT', stateName: 'Utah', population: 138144 },
  { city: 'Orange', stateId: 'CA', stateName: 'California', population: 137941 },
  { city: 'Cedar Rapids', stateId: 'IA', stateName: 'Iowa', population: 137904 },
  { city: 'Warren', stateId: 'MI', stateName: 'Michigan', population: 137686 },
  { city: 'Hampton', stateId: 'VA', stateName: 'Virginia', population: 137596 },
  { city: 'New Haven', stateId: 'CT', stateName: 'Connecticut', population: 137562 },
  { city: 'Pasadena', stateId: 'CA', stateName: 'California', population: 137195 },
  { city: 'Kent', stateId: 'WA', stateName: 'Washington', population: 136588 },
  { city: 'Dayton', stateId: 'OH', stateName: 'Ohio', population: 136346 },
  { city: 'Fargo', stateId: 'ND', stateName: 'North Dakota', population: 136285 },
  { city: 'Lewisville', stateId: 'TX', stateName: 'Texas', population: 135983 },
  { city: 'Carrollton', stateId: 'TX', stateName: 'Texas', population: 135456 },
  { city: 'Round Rock', stateId: 'TX', stateName: 'Texas', population: 135359 },
  { city: 'Sterling Heights', stateId: 'MI', stateName: 'Michigan', population: 134342 },
  { city: 'Santa Clara', stateId: 'CA', stateName: 'California', population: 133132 },
  { city: 'Norman', stateId: 'OK', stateName: 'Oklahoma', population: 131010 },
  { city: 'Columbia', stateId: 'MO', stateName: 'Missouri', population: 130900 },
  { city: 'Abilene', stateId: 'TX', stateName: 'Texas', population: 130501 },
  { city: 'Pearland', stateId: 'TX', stateName: 'Texas', population: 129620 },
  { city: 'Athens', stateId: 'GA', stateName: 'Georgia', population: 128691 },
  { city: 'College Station', stateId: 'TX', stateName: 'Texas', population: 128023 },
  { city: 'Clovis', stateId: 'CA', stateName: 'California', population: 127993 },
  { city: 'West Palm Beach', stateId: 'FL', stateName: 'Florida', population: 127744 },
  { city: 'Allentown', stateId: 'PA', stateName: 'Pennsylvania', population: 127138 },
  { city: 'North Charleston', stateId: 'SC', stateName: 'South Carolina', population: 126005 },
  { city: 'Simi Valley', stateId: 'CA', stateName: 'California', population: 125778 },
  { city: 'Topeka', stateId: 'KS', stateName: 'Kansas', population: 125467 },
  { city: 'Wilmington', stateId: 'NC', stateName: 'North Carolina', population: 125284 },
  { city: 'Lakeland', stateId: 'FL', stateName: 'Florida', population: 124990 },
  { city: 'Thousand Oaks', stateId: 'CA', stateName: 'California', population: 124229 },
  { city: 'Concord', stateId: 'CA', stateName: 'California', population: 124016 },
  { city: 'Rochester', stateId: 'MN', stateName: 'Minnesota', population: 123624 },
  { city: 'Vallejo', stateId: 'CA', stateName: 'California', population: 123475 },
  { city: 'Ann Arbor', stateId: 'MI', stateName: 'Michigan', population: 122925 },
  { city: 'Broken Arrow', stateId: 'OK', stateName: 'Oklahoma', population: 122756 },
  { city: 'Fairfield', stateId: 'CA', stateName: 'California', population: 122646 },
  { city: 'Lafayette', stateId: 'LA', stateName: 'Louisiana', population: 122280 },
  { city: 'Hartford', stateId: 'CT', stateName: 'Connecticut', population: 122129 },
  { city: 'Arvada', stateId: 'CO', stateName: 'Colorado', population: 121873 },
  { city: 'Berkeley', stateId: 'CA', stateName: 'California', population: 121749 },
  { city: 'Independence', stateId: 'MO', stateName: 'Missouri', population: 121629 },
  { city: 'Billings', stateId: 'MT', stateName: 'Montana', population: 121483 },
  { city: 'Cambridge', stateId: 'MA', stateName: 'Massachusetts', population: 121186 },
  { city: 'Lowell', stateId: 'MA', stateName: 'Massachusetts', population: 120418 },
  { city: 'Odessa', stateId: 'TX', stateName: 'Texas', population: 119748 },
  { city: 'High Point', stateId: 'NC', stateName: 'North Carolina', population: 118601 },
  { city: 'League City', stateId: 'TX', stateName: 'Texas', population: 118456 },
  { city: 'Antioch', stateId: 'CA', stateName: 'California', population: 118453 },
  { city: 'Richardson', stateId: 'TX', stateName: 'Texas', population: 118221 },
  { city: 'Goodyear', stateId: 'AZ', stateName: 'Arizona', population: 118186 },
  { city: 'Pompano Beach', stateId: 'FL', stateName: 'Florida', population: 118104 },
  { city: 'Nampa', stateId: 'ID', stateName: 'Idaho', population: 117350 },
  { city: 'Menifee', stateId: 'CA', stateName: 'California', population: 117041 },
  { city: 'Las Cruces', stateId: 'NM', stateName: 'New Mexico', population: 116998 },
  { city: 'Clearwater', stateId: 'FL', stateName: 'Florida', population: 116811 },
  { city: 'West Jordan', stateId: 'UT', stateName: 'Utah', population: 116688 },
  { city: 'New Braunfels', stateId: 'TX', stateName: 'Texas', population: 116477 },
  { city: 'Manchester', stateId: 'NH', stateName: 'New Hampshire', population: 116386 },
  { city: 'Miami Gardens', stateId: 'FL', stateName: 'Florida', population: 116173 },
  { city: 'Waterbury', stateId: 'CT', stateName: 'Connecticut', population: 115908 },
  { city: 'Provo', stateId: 'UT', stateName: 'Utah', population: 115479 },
  { city: 'Evansville', stateId: 'IN', stateName: 'Indiana', population: 115395 },
  { city: 'Richmond', stateId: 'CA', stateName: 'California', population: 115353 },
  { city: 'Westminster', stateId: 'CO', stateName: 'Colorado', population: 115302 },
  { city: 'Elgin', stateId: 'IL', stateName: 'Illinois', population: 114701 },
  { city: 'Conroe', stateId: 'TX', stateName: 'Texas', population: 114581 },
  { city: 'Greeley', stateId: 'CO', stateName: 'Colorado', population: 114363 },
  { city: 'Lansing', stateId: 'MI', stateName: 'Michigan', population: 114336 },
  { city: 'Buckeye', stateId: 'AZ', stateName: 'Arizona', population: 114334 },
  { city: 'Tuscaloosa', stateId: 'AL', stateName: 'Alabama', population: 114288 },
  { city: 'Allen', stateId: 'TX', stateName: 'Texas', population: 113746 },
  { city: 'Carlsbad', stateId: 'CA', stateName: 'California', population: 113575 },
  { city: 'Everett', stateId: 'WA', stateName: 'Washington', population: 113011 },
  { city: 'Springfield', stateId: 'IL', stateName: 'Illinois', population: 112949 },
  { city: 'Beaumont', stateId: 'TX', stateName: 'Texas', population: 112893 },
  { city: 'Murrieta', stateId: 'CA', stateName: 'California', population: 112539 },
  { city: 'Rio Rancho', stateId: 'NM', stateName: 'New Mexico', population: 112524 },
  { city: 'Temecula', stateId: 'CA', stateName: 'California', population: 112431 },
  { city: 'Concord', stateId: 'NC', stateName: 'North Carolina', population: 112395 },
  { city: 'Tyler', stateId: 'TX', stateName: 'Texas', population: 112219 },
  { city: 'Davie', stateId: 'FL', stateName: 'Florida', population: 112052 },
  { city: 'South Fulton', stateId: 'GA', stateName: 'Georgia', population: 112003 },
  { city: 'Peoria', stateId: 'IL', stateName: 'Illinois', population: 111696 },
  { city: 'Sparks', stateId: 'NV', stateName: 'Nevada', population: 111520 },
  { city: 'Gresham', stateId: 'OR', stateName: 'Oregon', population: 111507 },
  { city: 'Santa Maria', stateId: 'CA', stateName: 'California', population: 111346 },
  { city: 'Pueblo', stateId: 'CO', stateName: 'Colorado', population: 111166 },
  { city: 'Hillsboro', stateId: 'OR', stateName: 'Oregon', population: 110337 },
  { city: 'Sugar Land', stateId: 'TX', stateName: 'Texas', population: 109851 },
  { city: 'San Buenaventura (Ventura)', stateId: 'CA', stateName: 'California', population: 109831 },
  { city: 'Downey', stateId: 'CA', stateName: 'California', population: 109368 },
  { city: 'Costa Mesa', stateId: 'CA', stateName: 'California', population: 109131 },
  { city: 'Centennial', stateId: 'CO', stateName: 'Colorado', population: 108853 },
  { city: 'Edinburg', stateId: 'TX', stateName: 'Texas', population: 108733 },
  { city: 'Spokane Valley', stateId: 'WA', stateName: 'Washington', population: 108267 },
  { city: 'Jurupa Valley', stateId: 'CA', stateName: 'California', population: 108154 },
  { city: 'Bend', stateId: 'OR', stateName: 'Oregon', population: 106926 },
  { city: 'West Covina', stateId: 'CA', stateName: 'California', population: 106920 },
  { city: 'Boulder', stateId: 'CO', stateName: 'Colorado', population: 106803 },
  { city: 'Palm Coast', stateId: 'FL', stateName: 'Florida', population: 106729 },
  { city: 'Lee\'s Summit', stateId: 'MO', stateName: 'Missouri', population: 106419 },
  { city: 'Dearborn', stateId: 'MI', stateName: 'Michigan', population: 106377 },
  { city: 'Green Bay', stateId: 'WI', stateName: 'Wisconsin', population: 106311 },
  { city: 'St. George', stateId: 'UT', stateName: 'Utah', population: 106288 },
  { city: 'Brockton', stateId: 'MA', stateName: 'Massachusetts', population: 105788 },
  { city: 'Renton', stateId: 'WA', stateName: 'Washington', population: 105543 },
  { city: 'Sandy Springs', stateId: 'GA', stateName: 'Georgia', population: 105505 },
  { city: 'Rialto', stateId: 'CA', stateName: 'California', population: 104918 },
  { city: 'El Monte', stateId: 'CA', stateName: 'California', population: 104639 },
  { city: 'Vacaville', stateId: 'CA', stateName: 'California', population: 103994 },
  { city: 'Fishers', stateId: 'IN', stateName: 'Indiana', population: 103986 },
  { city: 'South Bend', stateId: 'IN', stateName: 'Indiana', population: 103713 },
  { city: 'Carmel', stateId: 'IN', stateName: 'Indiana', population: 103606 },
  { city: 'Yuma', stateId: 'AZ', stateName: 'Arizona', population: 103559 },
  { city: 'Burbank', stateId: 'CA', stateName: 'California', population: 103533 },
  { city: 'Lynn', stateId: 'MA', stateName: 'Massachusetts', population: 103489 },
  { city: 'Quincy', stateId: 'MA', stateName: 'Massachusetts', population: 103434 },
  { city: 'El Cajon', stateId: 'CA', stateName: 'California', population: 103291 },
  { city: 'Fayetteville', stateId: 'AR', stateName: 'Arkansas', population: 103134 },
  { city: 'Suffolk', stateId: 'VA', stateName: 'Virginia', population: 103105 },
  { city: 'San Mateo', stateId: 'CA', stateName: 'California', population: 103006 },
  { city: 'Chico', stateId: 'CA', stateName: 'California', population: 102911 },
  { city: 'Inglewood', stateId: 'CA', stateName: 'California', population: 102774 },
  { city: 'Wichita Falls', stateId: 'TX', stateName: 'Texas', population: 102372 },
  { city: 'Boca Raton', stateId: 'FL', stateName: 'Florida', population: 102238 },
  { city: 'Hesperia', stateId: 'CA', stateName: 'California', population: 101836 },
  { city: 'Daly City', stateId: 'CA', stateName: 'California', population: 101418 },
  { city: 'Georgetown', stateId: 'TX', stateName: 'Texas', population: 101344 },
  { city: 'New Bedford', stateId: 'MA', stateName: 'Massachusetts', population: 101318 },
  { city: 'Albany', stateId: 'NY', stateName: 'New York', population: 101317 },
  { city: 'Davenport', stateId: 'IA', stateName: 'Iowa', population: 100938 },
  { city: 'Plantation', stateId: 'FL', stateName: 'Florida', population: 100694 },
  { city: 'Deltona', stateId: 'FL', stateName: 'Florida', population: 100513 },
  { city: 'Federal Way', stateId: 'WA', stateName: 'Washington', population: 100252 },
  { city: 'San Angelo', stateId: 'TX', stateName: 'Texas', population: 100159 },
  { city: 'Tracy', stateId: 'CA', stateName: 'California', population: 100136 },
  { city: 'Sunrise', stateId: 'FL', stateName: 'Florida', population: 100128 },
  { city: 'Fort Myers', stateId: 'FL', stateName: 'Florida', population: 99918 },
  { city: 'Longmont', stateId: 'CO', stateName: 'Colorado', population: 99818 },
  { city: 'Kenosha', stateId: 'WI', stateName: 'Wisconsin', population: 99578 },
  { city: 'Vista', stateId: 'CA', stateName: 'California', population: 99322 },
  { city: 'Edmond', stateId: 'OK', stateName: 'Oklahoma', population: 99040 },
  { city: 'Beaverton', stateId: 'OR', stateName: 'Oregon', population: 98302 },
  { city: 'Norwalk', stateId: 'CA', stateName: 'California', population: 98230 },
  { city: 'Roanoke', stateId: 'VA', stateName: 'Virginia', population: 97912 },
  { city: 'Yakima', stateId: 'WA', stateName: 'Washington', population: 97390 },
  { city: 'Lawrence', stateId: 'KS', stateName: 'Kansas', population: 97271 },
  { city: 'Orem', stateId: 'UT', stateName: 'Utah', population: 96646 },
  { city: 'San Marcos', stateId: 'CA', stateName: 'California', population: 96620 },
  { city: 'Avondale', stateId: 'AZ', stateName: 'Arizona', population: 96609 },
  { city: 'Portsmouth', stateId: 'VA', stateName: 'Virginia', population: 96482 },
  { city: 'Temple', stateId: 'TX', stateName: 'Texas', population: 96267 },
  { city: 'Merced', stateId: 'CA', stateName: 'California', population: 96073 },
  { city: 'Reading', stateId: 'PA', stateName: 'Pennsylvania', population: 96000 },
  { city: 'Bellingham', stateId: 'WA', stateName: 'Washington', population: 95860 },
  { city: 'Mount Pleasant', stateId: 'SC', stateName: 'South Carolina', population: 95604 },
  { city: 'Kirkland', stateId: 'WA', stateName: 'Washington', population: 95499 },
  { city: 'O\'Fallon', stateId: 'MO', stateName: 'Missouri', population: 95355 },
  { city: 'Greenville', stateId: 'NC', stateName: 'North Carolina', population: 95138 },
  { city: 'Asheville', stateId: 'NC', stateName: 'North Carolina', population: 94992 },
  { city: 'Fall River', stateId: 'MA', stateName: 'Massachusetts', population: 94689 },
  { city: 'Manteca', stateId: 'CA', stateName: 'California', population: 94292 },
  { city: 'Indio', stateId: 'CA', stateName: 'California', population: 94275 },
  { city: 'Chino', stateId: 'CA', stateName: 'California', population: 94010 },
  { city: 'Norwalk', stateId: 'CT', stateName: 'Connecticut', population: 93661 },
  { city: 'Redding', stateId: 'CA', stateName: 'California', population: 93502 },
  { city: 'Lehi', stateId: 'UT', stateName: 'Utah', population: 93446 },
  { city: 'Livonia', stateId: 'MI', stateName: 'Michigan', population: 93113 },
  { city: 'Hoover', stateId: 'AL', stateName: 'Alabama', population: 93013 },
  { city: 'Erie', stateId: 'PA', stateName: 'Pennsylvania', population: 92940 },
  { city: 'Hemet', stateId: 'CA', stateName: 'California', population: 92912 },
  { city: 'North Port', stateId: 'FL', stateName: 'Florida', population: 92875 },
  { city: 'Sandy', stateId: 'UT', stateName: 'Utah', population: 92840 },
  { city: 'Roswell', stateId: 'GA', stateName: 'Georgia', population: 92227 },
  { city: 'Champaign', stateId: 'IL', stateName: 'Illinois', population: 91961 },
  { city: 'Nashua', stateId: 'NH', stateName: 'New Hampshire', population: 91851 },
  { city: 'Mission Viejo', stateId: 'CA', stateName: 'California', population: 91601 },
  { city: 'Bryan', stateId: 'TX', stateName: 'Texas', population: 91541 },
  { city: 'Carson', stateId: 'CA', stateName: 'California', population: 91358 },
  { city: 'Trenton', stateId: 'NJ', stateName: 'New Jersey', population: 91193 },
  { city: 'Compton', stateId: 'CA', stateName: 'California', population: 91129 },
  { city: 'South Gate', stateId: 'CA', stateName: 'California', population: 90805 },
  { city: 'Santa Monica', stateId: 'CA', stateName: 'California', population: 90729 },
  { city: 'Newton', stateId: 'MA', stateName: 'Massachusetts', population: 90700 },
  { city: 'Santa Fe', stateId: 'NM', stateName: 'New Mexico', population: 90551 },
  { city: 'Fort Smith', stateId: 'AR', stateName: 'Arkansas', population: 90507 },
  { city: 'Deerfield Beach', stateId: 'FL', stateName: 'Florida', population: 90507 },
  { city: 'Clifton', stateId: 'NJ', stateName: 'New Jersey', population: 90322 },
  { city: 'Lawton', stateId: 'OK', stateName: 'Oklahoma', population: 90027 },
  { city: 'Westminster', stateId: 'CA', stateName: 'California', population: 89537 },
  { city: 'Frederick', stateId: 'MD', stateName: 'Maryland', population: 89537 },
  { city: 'Springdale', stateId: 'AR', stateName: 'Arkansas', population: 89368 },
  { city: 'Lawrence', stateId: 'MA', stateName: 'Massachusetts', population: 89332 },
  { city: 'Troy', stateId: 'MI', stateName: 'Michigan', population: 89209 },
  { city: 'Franklin', stateId: 'TN', stateName: 'Tennessee', population: 89142 },
  { city: 'Danbury', stateId: 'CT', stateName: 'Connecticut', population: 88692 },
  { city: 'Ogden', stateId: 'UT', stateName: 'Utah', population: 88656 },
  { city: 'Mission', stateId: 'TX', stateName: 'Texas', population: 88574 },
  { city: 'Waukegan', stateId: 'IL', stateName: 'Illinois', population: 88570 },
  { city: 'Bloomington', stateId: 'MN', stateName: 'Minnesota', population: 88344 },
  { city: 'Folsom', stateId: 'CA', stateName: 'California', population: 88091 },
  { city: 'Duluth', stateId: 'MN', stateName: 'Minnesota', population: 87986 },
  { city: 'Melbourne', stateId: 'FL', stateName: 'Florida', population: 87561 },
  { city: 'Leander', stateId: 'TX', stateName: 'Texas', population: 87511 },
  { city: 'Mountain View', stateId: 'CA', stateName: 'California', population: 87316 },
  { city: 'Santa Barbara', stateId: 'CA', stateName: 'California', population: 87291 },
  { city: 'Lake Forest', stateId: 'CA', stateName: 'California', population: 87159 },
  { city: 'Citrus Heights', stateId: 'CA', stateName: 'California', population: 86909 },
  { city: 'Sioux City', stateId: 'IA', stateName: 'Iowa', population: 86875 },
  { city: 'Kennewick', stateId: 'WA', stateName: 'Washington', population: 86728 },
  { city: 'San Leandro', stateId: 'CA', stateName: 'California', population: 86571 },
  { city: 'Medford', stateId: 'OR', stateName: 'Oregon', population: 86301 },
  { city: 'Warner Robins', stateId: 'GA', stateName: 'Georgia', population: 86199 },
  { city: 'South Jordan', stateId: 'UT', stateName: 'Utah', population: 86156 },
  { city: 'Daytona Beach', stateId: 'FL', stateName: 'Florida', population: 86015 },
  { city: 'Baytown', stateId: 'TX', stateName: 'Texas', population: 86004 },
  { city: 'San Ramon', stateId: 'CA', stateName: 'California', population: 85924 },
  { city: 'Homestead', stateId: 'FL', stateName: 'Florida', population: 85796 },
  { city: 'Whittier', stateId: 'CA', stateName: 'California', population: 85589 },
  { city: 'Gastonia', stateId: 'NC', stateName: 'North Carolina', population: 85535 },
  { city: 'Auburn', stateId: 'WA', stateName: 'Washington', population: 85513 },
  { city: 'New Rochelle', stateId: 'NY', stateName: 'New York', population: 85512 },
  { city: 'Livermore', stateId: 'CA', stateName: 'California', population: 84867 },
  { city: 'Kissimmee', stateId: 'FL', stateName: 'Florida', population: 84756 },
  { city: 'Cranston', stateId: 'RI', stateName: 'Rhode Island', population: 84448 },
  { city: 'Layton', stateId: 'UT', stateName: 'Utah', population: 84348 },
  { city: 'Farmington Hills', stateId: 'MI', stateName: 'Michigan', population: 84173 },
  { city: 'Rancho Cordova', stateId: 'CA', stateName: 'California', population: 84113 },
  { city: 'Queen Creek', stateId: 'AZ', stateName: 'Arizona', population: 83781 },
  { city: 'Auburn', stateId: 'AL', stateName: 'Alabama', population: 83757 },
  { city: 'Longview', stateId: 'TX', stateName: 'Texas', population: 83668 },
  { city: 'Hawthorne', stateId: 'CA', stateName: 'California', population: 83633 },
  { city: 'Doral', stateId: 'FL', stateName: 'Florida', population: 83625 },
  { city: 'Warwick', stateId: 'RI', stateName: 'Rhode Island', population: 83554 },
  { city: 'Miami Beach', stateId: 'FL', stateName: 'Florida', population: 83251 },
  { city: 'Castle Rock', stateId: 'CO', stateName: 'Colorado', population: 83213 },
  { city: 'Boynton Beach', stateId: 'FL', stateName: 'Florida', population: 83095 },
  { city: 'Perris', stateId: 'CA', stateName: 'California', population: 83032 },
  { city: 'Redwood City', stateId: 'CA', stateName: 'California', population: 82982 },
  { city: 'Newport Beach', stateId: 'CA', stateName: 'California', population: 82970 },
  { city: 'Brooklyn Park', stateId: 'MN', stateName: 'Minnesota', population: 82893 },
  { city: 'Westland', stateId: 'MI', stateName: 'Michigan', population: 82745 },
  { city: 'Buena Park', stateId: 'CA', stateName: 'California', population: 82611 },
  { city: 'Jonesboro', stateId: 'AR', stateName: 'Arkansas', population: 82384 },
  { city: 'Largo', stateId: 'FL', stateName: 'Florida', population: 82337 },
  { city: 'Redmond', stateId: 'WA', stateName: 'Washington', population: 82195 },
  { city: 'Somerville', stateId: 'MA', stateName: 'Massachusetts', population: 82149 },
  { city: 'Cicero', stateId: 'IL', stateName: 'Illinois', population: 82090 },
  { city: 'Pasco', stateId: 'WA', stateName: 'Washington', population: 81724 },
  { city: 'Johns Creek', stateId: 'GA', stateName: 'Georgia', population: 81167 },
  { city: 'Lake Charles', stateId: 'LA', stateName: 'Louisiana', population: 81157 },
  { city: 'Pharr', stateId: 'TX', stateName: 'Texas', population: 81142 },
  { city: 'Loveland', stateId: 'CO', stateName: 'Colorado', population: 81102 },
  { city: 'Mansfield', stateId: 'TX', stateName: 'Texas', population: 80803 },
  { city: 'Woodbury', stateId: 'MN', stateName: 'Minnesota', population: 80596 },
  { city: 'Lynchburg', stateId: 'VA', stateName: 'Virginia', population: 80301 },
  { city: 'Alhambra', stateId: 'CA', stateName: 'California', population: 80279 },
  { city: 'Flower Mound', stateId: 'TX', stateName: 'Texas', population: 79990 },
  { city: 'Bloomington', stateId: 'IN', stateName: 'Indiana', population: 79986 },
  { city: 'Rapid City', stateId: 'SD', stateName: 'South Dakota', population: 79894 },
  { city: 'Milpitas', stateId: 'CA', stateName: 'California', population: 79746 },
  { city: 'Flint', stateId: 'MI', stateName: 'Michigan', population: 79735 },
  { city: 'Upland', stateId: 'CA', stateName: 'California', population: 79684 },
  { city: 'Bethlehem', stateId: 'PA', stateName: 'Pennsylvania', population: 79453 },
  { city: 'Parma', stateId: 'OH', stateName: 'Ohio', population: 79350 },
  { city: 'Bloomington', stateId: 'IL', stateName: 'Illinois', population: 79232 },
  { city: 'Bowling Green', stateId: 'KY', stateName: 'Kentucky', population: 79076 },
  { city: 'Tustin', stateId: 'CA', stateName: 'California', population: 78863 },
  { city: 'Alameda', stateId: 'CA', stateName: 'California', population: 78795 },
  { city: 'Missouri City', stateId: 'TX', stateName: 'Texas', population: 78582 },
  { city: 'Wyoming', stateId: 'MI', stateName: 'Michigan', population: 78559 },
  { city: 'Plymouth', stateId: 'MN', stateName: 'Minnesota', population: 78551 },
  { city: 'Lakewood', stateId: 'CA', stateName: 'California', population: 78494 },
  { city: 'Cedar Park', stateId: 'TX', stateName: 'Texas', population: 78380 },
  { city: 'Rochester Hills', stateId: 'MI', stateName: 'Michigan', population: 78330 },
  { city: 'Broomfield', stateId: 'CO', stateName: 'Colorado', population: 78323 },
  { city: 'Mableton', stateId: 'GA', stateName: 'Georgia', population: 78314 },
  { city: 'Missoula', stateId: 'MT', stateName: 'Montana', population: 78204 },
  { city: 'Racine', stateId: 'WI', stateName: 'Wisconsin', population: 78057 },
  { city: 'Lakeville', stateId: 'MN', stateName: 'Minnesota', population: 77971 },
  { city: 'Bismarck', stateId: 'ND', stateName: 'North Dakota', population: 77772 },
  { city: 'Flagstaff', stateId: 'AZ', stateName: 'Arizona', population: 77539 },
  { city: 'Chino Hills', stateId: 'CA', stateName: 'California', population: 77418 },
  { city: 'Pittsburg', stateId: 'CA', stateName: 'California', population: 77131 },
  { city: 'Schaumburg', stateId: 'IL', stateName: 'Illinois', population: 77099 },
  { city: 'Pawtucket', stateId: 'RI', stateName: 'Rhode Island', population: 76996 },
  { city: 'Napa', stateId: 'CA', stateName: 'California', population: 76921 },
  { city: 'Southfield', stateId: 'MI', stateName: 'Michigan', population: 76874 },
  { city: 'Ankeny', stateId: 'IA', stateName: 'Iowa', population: 76727 },
  { city: 'Iowa City', stateId: 'IA', stateName: 'Iowa', population: 76710 },
  { city: 'Maricopa', stateId: 'AZ', stateName: 'Arizona', population: 76654 },
  { city: 'Lauderhill', stateId: 'FL', stateName: 'Florida', population: 76627 },
  { city: 'Marysville', stateId: 'WA', stateName: 'Washington', population: 76209 },
  { city: 'Hammond', stateId: 'IN', stateName: 'Indiana', population: 76030 },
  { city: 'Evanston', stateId: 'IL', stateName: 'Illinois', population: 76006 },
  { city: 'Apex', stateId: 'NC', stateName: 'North Carolina', population: 75977 },
  { city: 'Scranton', stateId: 'PA', stateName: 'Pennsylvania', population: 75905 },
  { city: 'New Britain', stateId: 'CT', stateName: 'Connecticut', population: 75871 },
  { city: 'Rock Hill', stateId: 'SC', stateName: 'South Carolina', population: 75798 },
  { city: 'Bellflower', stateId: 'CA', stateName: 'California', population: 75716 },
  { city: 'Pleasanton', stateId: 'CA', stateName: 'California', population: 75664 },
  { city: 'Rogers', stateId: 'AR', stateName: 'Arkansas', population: 75639 },
  { city: 'Arlington Heights', stateId: 'IL', stateName: 'Illinois', population: 75596 },
  { city: 'Appleton', stateId: 'WI', stateName: 'Wisconsin', population: 75344 },
  { city: 'Noblesville', stateId: 'IN', stateName: 'Indiana', population: 75239 },
  { city: 'Blaine', stateId: 'MN', stateName: 'Minnesota', population: 75172 },
  { city: 'Tamarac', stateId: 'FL', stateName: 'Florida', population: 75147 },
  { city: 'Rocklin', stateId: 'CA', stateName: 'California', population: 75129 },
  { city: 'Apple Valley', stateId: 'CA', stateName: 'California', population: 75029 },
  { city: 'Bolingbrook', stateId: 'IL', stateName: 'Illinois', population: 74756 },
  { city: 'Gulfport', stateId: 'MS', stateName: 'Mississippi', population: 74621 },
  { city: 'Bayonne', stateId: 'NJ', stateName: 'New Jersey', population: 74532 },
  { city: 'Greenville', stateId: 'SC', stateName: 'South Carolina', population: 74371 },
  { city: 'San Marcos', stateId: 'TX', stateName: 'Texas', population: 74316 },
  { city: 'Redlands', stateId: 'CA', stateName: 'California', population: 74279 },
  { city: 'West Des Moines', stateId: 'IA', stateName: 'Iowa', population: 73664 },
  { city: 'Johnson City', stateId: 'TN', stateName: 'Tennessee', population: 73635 },
  { city: 'Lake Elsinore', stateId: 'CA', stateName: 'California', population: 73595 },
  { city: 'Framingham', stateId: 'MA', stateName: 'Massachusetts', population: 73361 },
  { city: 'Kalamazoo', stateId: 'MI', stateName: 'Michigan', population: 73290 },
  { city: 'Wilmington', stateId: 'DE', stateName: 'Delaware', population: 73176 },
  { city: 'Caldwell', stateId: 'ID', stateName: 'Idaho', population: 73088 },
  { city: 'Turlock', stateId: 'CA', stateName: 'California', population: 72888 },
  { city: 'Maple Grove', stateId: 'MN', stateName: 'Minnesota', population: 72739 },
  { city: 'Tulare', stateId: 'CA', stateName: 'California', population: 72601 },
  { city: 'St. Charles', stateId: 'MO', stateName: 'Missouri', population: 72458 },
  { city: 'Eau Claire', stateId: 'WI', stateName: 'Wisconsin', population: 72331 },
  { city: 'Harlingen', stateId: 'TX', stateName: 'Texas', population: 72234 },
  { city: 'St. Cloud', stateId: 'MN', stateName: 'Minnesota', population: 72145 },
  { city: 'Mount Vernon', stateId: 'NY', stateName: 'New York', population: 71999 },
  { city: 'East Orange', stateId: 'NJ', stateName: 'New Jersey', population: 71850 },
  { city: 'Lafayette', stateId: 'IN', stateName: 'Indiana', population: 71757 },
  { city: 'Camden', stateId: 'NJ', stateName: 'New Jersey', population: 71749 },
  { city: 'Dothan', stateId: 'AL', stateName: 'Alabama', population: 71650 },
  { city: 'Waukesha', stateId: 'WI', stateName: 'Wisconsin', population: 71461 },
  { city: 'North Richland Hills', stateId: 'TX', stateName: 'Texas', population: 71436 },
  { city: 'St. Joseph', stateId: 'MO', stateName: 'Missouri', population: 71098 },
  { city: 'St. Cloud', stateId: 'FL', stateName: 'Florida', population: 71036 },
  { city: 'Jacksonville', stateId: 'NC', stateName: 'North Carolina', population: 70840 },
  { city: 'Walnut Creek', stateId: 'CA', stateName: 'California', population: 70817 },
  { city: 'Eastvale', stateId: 'CA', stateName: 'California', population: 70751 },
  { city: 'Passaic', stateId: 'NJ', stateName: 'New Jersey', population: 70722 },
  { city: 'Conway', stateId: 'AR', stateName: 'Arkansas', population: 70711 },
  { city: 'Gaithersburg', stateId: 'MD', stateName: 'Maryland', population: 70686 },
  { city: 'Weston', stateId: 'FL', stateName: 'Florida', population: 70674 },
  { city: 'Grand Junction', stateId: 'CO', stateName: 'Colorado', population: 70554 },
  { city: 'Dublin', stateId: 'CA', stateName: 'California', population: 70544 },
  { city: 'Ocala', stateId: 'FL', stateName: 'Florida', population: 70251 },
  { city: 'Commerce City', stateId: 'CO', stateName: 'Colorado', population: 70245 },
  { city: 'Delray Beach', stateId: 'FL', stateName: 'Florida', population: 70140 },
  { city: 'Camarillo', stateId: 'CA', stateName: 'California', population: 69881 },
  { city: 'Shawnee', stateId: 'KS', stateName: 'Kansas', population: 69724 },
  { city: 'Portland', stateId: 'ME', stateName: 'Maine', population: 69568 },
  { city: 'Idaho Falls', stateId: 'ID', stateName: 'Idaho', population: 69523 },
  { city: 'Schenectady', stateId: 'NY', stateName: 'New York', population: 69495 },
  { city: 'Jackson', stateId: 'TN', stateName: 'Tennessee', population: 69303 },
  { city: 'Baldwin Park', stateId: 'CA', stateName: 'California', population: 69247 },
  { city: 'Canton', stateId: 'OH', stateName: 'Ohio', population: 69211 },
  { city: 'Yuba City', stateId: 'CA', stateName: 'California', population: 69148 },
  { city: 'Madera', stateId: 'CA', stateName: 'California', population: 69094 },
  { city: 'Ames', stateId: 'IA', stateName: 'Iowa', population: 69026 },
  { city: 'Casa Grande', stateId: 'AZ', stateName: 'Arizona', population: 68927 },
  { city: 'Decatur', stateId: 'IL', stateName: 'Illinois', population: 68763 },
  { city: 'Lodi', stateId: 'CA', stateName: 'California', population: 68642 },
  { city: 'Rockville', stateId: 'MD', stateName: 'Maryland', population: 68417 },
  { city: 'Haverhill', stateId: 'MA', stateName: 'Massachusetts', population: 68291 },
  { city: 'Greenwood', stateId: 'IN', stateName: 'Indiana', population: 68175 },
  { city: 'Rowlett', stateId: 'TX', stateName: 'Texas', population: 68123 },
  { city: 'Redondo Beach', stateId: 'CA', stateName: 'California', population: 68075 },
  { city: 'Novi', stateId: 'MI', stateName: 'Michigan', population: 67675 },
  { city: 'Palo Alto', stateId: 'CA', stateName: 'California', population: 67658 },
  { city: 'Gary', stateId: 'IN', stateName: 'Indiana', population: 67555 },
  { city: 'Waterloo', stateId: 'IA', stateName: 'Iowa', population: 67477 },
  { city: 'Alpharetta', stateId: 'GA', stateName: 'Georgia', population: 67275 },
  { city: 'Oshkosh', stateId: 'WI', stateName: 'Wisconsin', population: 67242 },
  { city: 'Eagan', stateId: 'MN', stateName: 'Minnesota', population: 67240 },
  { city: 'Davis', stateId: 'CA', stateName: 'California', population: 67125 },
  { city: 'Huntersville', stateId: 'NC', stateName: 'North Carolina', population: 67087 },
  { city: 'Sanford', stateId: 'FL', stateName: 'Florida', population: 66919 },
  { city: 'Union City', stateId: 'NJ', stateName: 'New Jersey', population: 66918 },
  { city: 'Pflugerville', stateId: 'TX', stateName: 'Texas', population: 66819 },
  { city: 'Albany', stateId: 'GA', stateName: 'Georgia', population: 66705 },
  { city: 'Malden', stateId: 'MA', stateName: 'Massachusetts', population: 66693 },
  { city: 'Port Orange', stateId: 'FL', stateName: 'Florida', population: 66556 },
  { city: 'Yorba Linda', stateId: 'CA', stateName: 'California', population: 66489 },
  { city: 'Sammamish', stateId: 'WA', stateName: 'Washington', population: 66474 },
  { city: 'Janesville', stateId: 'WI', stateName: 'Wisconsin', population: 66428 },
  { city: 'Brentwood', stateId: 'CA', stateName: 'California', population: 66286 },
  { city: 'Shoreline', stateId: 'WA', stateName: 'Washington', population: 66251 },
  { city: 'Union City', stateId: 'CA', stateName: 'California', population: 66196 },
  { city: 'Victoria', stateId: 'TX', stateName: 'Texas', population: 66020 },
  { city: 'Palatine', stateId: 'IL', stateName: 'Illinois', population: 65951 },
  { city: 'Skokie', stateId: 'IL', stateName: 'Illinois', population: 65850 },
  { city: 'Waltham', stateId: 'MA', stateName: 'Massachusetts', population: 65849 },
  { city: 'Kyle', stateId: 'TX', stateName: 'Texas', population: 65833 },
  { city: 'Lorain', stateId: 'OH', stateName: 'Ohio', population: 65751 },
  { city: 'Cheyenne', stateId: 'WY', stateName: 'Wyoming', population: 65704 },
  { city: 'Parker', stateId: 'CO', stateName: 'Colorado', population: 65473 },
  { city: 'Muncie', stateId: 'IN', stateName: 'Indiana', population: 65320 },
  { city: 'Burnsville', stateId: 'MN', stateName: 'Minnesota', population: 64864 },
  { city: 'Bellevue', stateId: 'NE', stateName: 'Nebraska', population: 64777 },
  { city: 'South San Francisco', stateId: 'CA', stateName: 'California', population: 64660 },
  { city: 'Kenner', stateId: 'LA', stateName: 'Louisiana', population: 64650 },
  { city: 'North Little Rock', stateId: 'AR', stateName: 'Arkansas', population: 64498 },
  { city: 'Richland', stateId: 'WA', stateName: 'Washington', population: 64372 },
  { city: 'Millcreek', stateId: 'UT', stateName: 'Utah', population: 64217 },
  { city: 'Laguna Niguel', stateId: 'CA', stateName: 'California', population: 64185 },
  { city: 'Madison', stateId: 'AL', stateName: 'Alabama', population: 64029 },
  { city: 'Chapel Hill', stateId: 'NC', stateName: 'North Carolina', population: 64028 },
  { city: 'Hamilton', stateId: 'OH', stateName: 'Ohio', population: 63953 },
  { city: 'Hendersonville', stateId: 'TN', stateName: 'Tennessee', population: 63947 },
  { city: 'Moore', stateId: 'OK', stateName: 'Oklahoma', population: 63845 },
  { city: 'Coon Rapids', stateId: 'MN', stateName: 'Minnesota', population: 63807 },
  { city: 'Utica', stateId: 'NY', stateName: 'New York', population: 63660 },
  { city: 'Lynwood', stateId: 'CA', stateName: 'California', population: 63596 },
  { city: 'Porterville', stateId: 'CA', stateName: 'California', population: 63517 },
  { city: 'Palm Beach Gardens', stateId: 'FL', stateName: 'Florida', population: 63284 },
  { city: 'Wellington', stateId: 'FL', stateName: 'Florida', population: 63258 },
  { city: 'Bossier City', stateId: 'LA', stateName: 'Louisiana', population: 63218 },
  { city: 'Marietta', stateId: 'GA', stateName: 'Georgia', population: 63122 },
  { city: 'Westfield', stateId: 'IN', stateName: 'Indiana', population: 62994 },
  { city: 'Jupiter', stateId: 'FL', stateName: 'Florida', population: 62987 },
  { city: 'Woodland', stateId: 'CA', stateName: 'California', population: 62983 },
  { city: 'Wylie', stateId: 'TX', stateName: 'Texas', population: 62954 },
  { city: 'Eden Prairie', stateId: 'MN', stateName: 'Minnesota', population: 62905 },
  { city: 'Apopka', stateId: 'FL', stateName: 'Florida', population: 62777 },
  { city: 'Lakewood', stateId: 'WA', stateName: 'Washington', population: 62709 },
  { city: 'Council Bluffs', stateId: 'IA', stateName: 'Iowa', population: 62665 },
  { city: 'San Clemente', stateId: 'CA', stateName: 'California', population: 62627 },
  { city: 'Santa Cruz', stateId: 'CA', stateName: 'California', population: 62581 },
  { city: 'White Plains', stateId: 'NY', stateName: 'New York', population: 62561 },
  { city: 'Pontiac', stateId: 'MI', stateName: 'Michigan', population: 62528 },
  { city: 'Marana', stateId: 'AZ', stateName: 'Arizona', population: 62380 },
  { city: 'Herriman', stateId: 'UT', stateName: 'Utah', population: 62352 },
  { city: 'North Miami', stateId: 'FL', stateName: 'Florida', population: 62202 },
  { city: 'Bristol', stateId: 'CT', stateName: 'Connecticut', population: 62195 },
  { city: 'Vineland', stateId: 'NJ', stateName: 'New Jersey', population: 62070 },
  { city: 'Corvallis', stateId: 'OR', stateName: 'Oregon', population: 61993 },
  { city: 'Taunton', stateId: 'MA', stateName: 'Massachusetts', population: 61936 },
  { city: 'Bentonville', stateId: 'AR', stateName: 'Arkansas', population: 61791 },
  { city: 'Taylor', stateId: 'MI', stateName: 'Michigan', population: 61544 },
  { city: 'St. Peters', stateId: 'MO', stateName: 'Missouri', population: 61398 },
  { city: 'La Habra', stateId: 'CA', stateName: 'California', population: 61391 },
  { city: 'Burlington', stateId: 'NC', stateName: 'North Carolina', population: 61365 },
  { city: 'Blue Springs', stateId: 'MO', stateName: 'Missouri', population: 61246 },
  { city: 'Little Elm', stateId: 'TX', stateName: 'Texas', population: 61219 },
  { city: 'Springfield', stateId: 'OR', stateName: 'Oregon', population: 61182 },
  { city: 'Encinitas', stateId: 'CA', stateName: 'California', population: 61137 },
  { city: 'Dearborn Heights', stateId: 'MI', stateName: 'Michigan', population: 61040 },
  { city: 'Stonecrest', stateId: 'GA', stateName: 'Georgia', population: 61015 },
  { city: 'Meriden', stateId: 'CT', stateName: 'Connecticut', population: 60849 },
  { city: 'La Mesa', stateId: 'CA', stateName: 'California', population: 60767 },
  { city: 'Revere', stateId: 'MA', stateName: 'Massachusetts', population: 60702 },
  { city: 'Owensboro', stateId: 'KY', stateName: 'Kentucky', population: 60675 },
  { city: 'Margate', stateId: 'FL', stateName: 'Florida', population: 60650 },
  { city: 'Montebello', stateId: 'CA', stateName: 'California', population: 60617 },
  { city: 'Hanford', stateId: 'CA', stateName: 'California', population: 60594 },
  { city: 'Eagle Mountain', stateId: 'UT', stateName: 'Utah', population: 60575 },
  { city: 'Kannapolis', stateId: 'NC', stateName: 'North Carolina', population: 60521 },
  { city: 'Gilroy', stateId: 'CA', stateName: 'California', population: 60390 },
  { city: 'Smyrna', stateId: 'TN', stateName: 'Tennessee', population: 60302 },
  { city: 'Weymouth', stateId: 'MA', stateName: 'Massachusetts', population: 60159 },
  { city: 'Kokomo', stateId: 'IN', stateName: 'Indiana', population: 60093 },
  { city: 'Great Falls', stateId: 'MT', stateName: 'Montana', population: 60013 },
  { city: 'Euless', stateId: 'TX', stateName: 'Texas', population: 60010 },
  { city: 'Winter Haven', stateId: 'FL', stateName: 'Florida', population: 59975 },
  { city: 'San Rafael', stateId: 'CA', stateName: 'California', population: 59961 },
  { city: 'Medford', stateId: 'MA', stateName: 'Massachusetts', population: 59898 },
  { city: 'Grand Forks', stateId: 'ND', stateName: 'North Dakota', population: 59845 },
  { city: 'West Allis', stateId: 'WI', stateName: 'Wisconsin', population: 59784 },
  { city: 'Coconut Creek', stateId: 'FL', stateName: 'Florida', population: 59721 },
  { city: 'Hempstead', stateId: 'NY', stateName: 'New York', population: 59569 },
  { city: 'Beaumont', stateId: 'CA', stateName: 'California', population: 59502 },
  { city: 'Lenexa', stateId: 'KS', stateName: 'Kansas', population: 59427 },
  { city: 'Spring Hill', stateId: 'TN', stateName: 'Tennessee', population: 59398 },
  { city: 'Petaluma', stateId: 'CA', stateName: 'California', population: 59393 },
  { city: 'Brookhaven', stateId: 'GA', stateName: 'Georgia', population: 59370 },
  { city: 'Pico Rivera', stateId: 'CA', stateName: 'California', population: 59363 },
  { city: 'Hoboken', stateId: 'NJ', stateName: 'New Jersey', population: 59149 },
  { city: 'Youngstown', stateId: 'OH', stateName: 'Ohio', population: 59123 },
  { city: 'Santee', stateId: 'CA', stateName: 'California', population: 59104 },
  { city: 'Lake Havasu City', stateId: 'AZ', stateName: 'Arizona', population: 59037 },
  { city: 'Dubuque', stateId: 'IA', stateName: 'Iowa', population: 58987 },
  { city: 'Gardena', stateId: 'CA', stateName: 'California', population: 58921 },
  { city: 'Des Plaines', stateId: 'IL', stateName: 'Illinois', population: 58832 },
  { city: 'Casper', stateId: 'WY', stateName: 'Wyoming', population: 58823 },
  { city: 'Cupertino', stateId: 'CA', stateName: 'California', population: 58710 },
  { city: 'Lacey', stateId: 'WA', stateName: 'Washington', population: 58644 },
  { city: 'Terre Haute', stateId: 'IN', stateName: 'Indiana', population: 58531 },
  { city: 'Midwest City', stateId: 'OK', stateName: 'Oklahoma', population: 58505 },
  { city: 'National City', stateId: 'CA', stateName: 'California', population: 58460 },
  { city: 'Lancaster', stateId: 'PA', stateName: 'Pennsylvania', population: 58441 },
  { city: 'Bowie', stateId: 'MD', stateName: 'Maryland', population: 58421 },
  { city: 'Royal Oak', stateId: 'MI', stateName: 'Michigan', population: 58251 },
  { city: 'Pocatello', stateId: 'ID', stateName: 'Idaho', population: 58231 },
  { city: 'Bradenton', stateId: 'FL', stateName: 'Florida', population: 58184 },
  { city: 'Carson', stateId: 'NV', stateName: 'Nevada', population: 58148 },
  { city: 'Springfield', stateId: 'OH', stateName: 'Ohio', population: 58138 },
  { city: 'St. Clair Shores', stateId: 'MI', stateName: 'Michigan', population: 58077 },
  { city: 'Orland Park', stateId: 'IL', stateName: 'Illinois', population: 58020 },
  { city: 'Monterey Park', stateId: 'CA', stateName: 'California', population: 57996 },
  { city: 'Decatur', stateId: 'AL', stateName: 'Alabama', population: 57974 },
  { city: 'Bozeman', stateId: 'MT', stateName: 'Montana', population: 57894 },
  { city: 'Texas City', stateId: 'TX', stateName: 'Texas', population: 57875 },
  { city: 'Taylorsville', stateId: 'UT', stateName: 'Utah', population: 57819 },
  { city: 'Sarasota', stateId: 'FL', stateName: 'Florida', population: 57764 },
  { city: 'Southaven', stateId: 'MS', stateName: 'Mississippi', population: 57493 },
  { city: 'New Brunswick', stateId: 'NJ', stateName: 'New Jersey', population: 57487 },
  { city: 'Saratoga Springs', stateId: 'UT', stateName: 'Utah', population: 57411 },
  { city: 'Coeur d\'Alene', stateId: 'ID', stateName: 'Idaho', population: 57355 },
  { city: 'Tigard', stateId: 'OR', stateName: 'Oregon', population: 57301 },
  { city: 'Smyrna', stateId: 'GA', stateName: 'Georgia', population: 57177 },
  { city: 'Albany', stateId: 'OR', stateName: 'Oregon', population: 57156 },
  { city: 'Bonita Springs', stateId: 'FL', stateName: 'Florida', population: 57112 },
  { city: 'Kingsport', stateId: 'TN', stateName: 'Tennessee', population: 57109 },
  { city: 'Kettering', stateId: 'OH', stateName: 'Ohio', population: 57028 },
  { city: 'Perth Amboy', stateId: 'NJ', stateName: 'New Jersey', population: 56939 },
  { city: 'Logan', stateId: 'UT', stateName: 'Utah', population: 56770 },
  { city: 'Wake Forest', stateId: 'NC', stateName: 'North Carolina', population: 56764 },
  { city: 'DeSoto', stateId: 'TX', stateName: 'Texas', population: 56711 },
  { city: 'Bartlett', stateId: 'TN', stateName: 'Tennessee', population: 56708 },
  { city: 'Oak Lawn', stateId: 'IL', stateName: 'Illinois', population: 56531 },
  { city: 'Plainfield', stateId: 'NJ', stateName: 'New Jersey', population: 56507 },
  { city: 'Highland', stateId: 'CA', stateName: 'California', population: 56499 },
  { city: 'Olympia', stateId: 'WA', stateName: 'Washington', population: 56271 },
  { city: 'Lincoln', stateId: 'CA', stateName: 'California', population: 56268 },
  { city: 'Burleson', stateId: 'TX', stateName: 'Texas', population: 56253 },
  { city: 'Fountain Valley', stateId: 'CA', stateName: 'California', population: 56036 },
  { city: 'West Sacramento', stateId: 'CA', stateName: 'California', population: 55991 },
  { city: 'Anderson', stateId: 'IN', stateName: 'Indiana', population: 55851 },
  { city: 'Port Arthur', stateId: 'TX', stateName: 'Texas', population: 55799 },
  { city: 'Valdosta', stateId: 'GA', stateName: 'Georgia', population: 55667 },
  { city: 'Twin Falls', stateId: 'ID', stateName: 'Idaho', population: 55589 },
  { city: 'San Jacinto', stateId: 'CA', stateName: 'California', population: 55515 },
  { city: 'Mount Prospect', stateId: 'IL', stateName: 'Illinois', population: 55460 },
  { city: 'Peabody', stateId: 'MA', stateName: 'Massachusetts', population: 55418 },
  { city: 'Chicopee', stateId: 'MA', stateName: 'Massachusetts', population: 55381 },
  { city: 'West Haven', stateId: 'CT', stateName: 'Connecticut', population: 55379 },
  { city: 'Apple Valley', stateId: 'MN', stateName: 'Minnesota', population: 55272 },
  { city: 'Berwyn', stateId: 'IL', stateName: 'Illinois', population: 55152 },
  { city: 'Tinley Park', stateId: 'IL', stateName: 'Illinois', population: 54856 },
  { city: 'Kentwood', stateId: 'MI', stateName: 'Michigan', population: 54768 },
  { city: 'Manhattan', stateId: 'KS', stateName: 'Kansas', population: 54700 },
  { city: 'Fulshear', stateId: 'TX', stateName: 'Texas', population: 54629 },
  { city: 'Rocky Mount', stateId: 'NC', stateName: 'North Carolina', population: 54541 },
  { city: 'Arcadia', stateId: 'CA', stateName: 'California', population: 54472 },
  { city: 'Yucaipa', stateId: 'CA', stateName: 'California', population: 54465 },
  { city: 'Methuen', stateId: 'MA', stateName: 'Massachusetts', population: 54272 },
  { city: 'Pensacola', stateId: 'FL', stateName: 'Florida', population: 53898 },
  { city: 'Wheaton', stateId: 'IL', stateName: 'Illinois', population: 53741 },
  { city: 'Elkhart', stateId: 'IN', stateName: 'Indiana', population: 53690 },
  { city: 'Joplin', stateId: 'MO', stateName: 'Missouri', population: 53605 },
  { city: 'Elyria', stateId: 'OH', stateName: 'Ohio', population: 53604 },
  { city: 'Edina', stateId: 'MN', stateName: 'Minnesota', population: 53564 },
  { city: 'Rockwall', stateId: 'TX', stateName: 'Texas', population: 53547 },
  { city: 'Galveston', stateId: 'TX', stateName: 'Texas', population: 53538 },
  { city: 'Colton', stateId: 'CA', stateName: 'California', population: 53528 },
  { city: 'Pinellas Park', stateId: 'FL', stateName: 'Florida', population: 53503 },
  { city: 'Placentia', stateId: 'CA', stateName: 'California', population: 53395 },
  { city: 'Normal', stateId: 'IL', stateName: 'Illinois', population: 53304 },
  { city: 'Grand Island', stateId: 'NE', stateName: 'Nebraska', population: 53250 },
  { city: 'Delano', stateId: 'CA', stateName: 'California', population: 53198 },
  { city: 'Palm Desert', stateId: 'CA', stateName: 'California', population: 53147 },
  { city: 'West New York', stateId: 'NJ', stateName: 'New Jersey', population: 52975 },
  { city: 'Oak Park', stateId: 'IL', stateName: 'Illinois', population: 52947 },
  { city: 'Jeffersonville', stateId: 'IN', stateName: 'Indiana', population: 52912 },
  { city: 'Mooresville', stateId: 'NC', stateName: 'North Carolina', population: 52884 },
  { city: 'Minnetonka', stateId: 'MN', stateName: 'Minnesota', population: 52651 },
  { city: 'Summerville', stateId: 'SC', stateName: 'South Carolina', population: 52625 },
  { city: 'Cathedral City', stateId: 'CA', stateName: 'California', population: 52517 },
  { city: 'Gallatin', stateId: 'TN', stateName: 'Tennessee', population: 52489 },
  { city: 'Novato', stateId: 'CA', stateName: 'California', population: 52311 },
  { city: 'Diamond Bar', stateId: 'CA', stateName: 'California', population: 52292 },
  { city: 'Middletown', stateId: 'OH', stateName: 'Ohio', population: 52291 },
  { city: 'Battle Creek', stateId: 'MI', stateName: 'Michigan', population: 52205 },
  { city: 'Huntington Park', stateId: 'CA', stateName: 'California', population: 52166 },
  { city: 'Burien', stateId: 'WA', stateName: 'Washington', population: 52046 },
  { city: 'Columbus', stateId: 'IN', stateName: 'Indiana', population: 51970 },
  { city: 'Collierville', stateId: 'TN', stateName: 'Tennessee', population: 51951 },
  { city: 'Everett', stateId: 'MA', stateName: 'Massachusetts', population: 51825 },
  { city: 'Dunwoody', stateId: 'GA', stateName: 'Georgia', population: 51795 },
  { city: 'Bothell', stateId: 'WA', stateName: 'Washington', population: 51770 },
  { city: 'Celina', stateId: 'TX', stateName: 'Texas', population: 51661 },
  { city: 'Lebanon', stateId: 'TN', stateName: 'Tennessee', population: 51501 },
  { city: 'Prescott Valley', stateId: 'AZ', stateName: 'Arizona', population: 51440 },
  { city: 'Newark', stateId: 'OH', stateName: 'Ohio', population: 51424 },
  { city: 'Watsonville', stateId: 'CA', stateName: 'California', population: 51320 },
  { city: 'Grapevine', stateId: 'TX', stateName: 'Texas', population: 51320 },
  { city: 'Florissant', stateId: 'MO', stateName: 'Missouri', population: 51290 },
  { city: 'Ocoee', stateId: 'FL', stateName: 'Florida', population: 51269 },
  { city: 'Paramount', stateId: 'CA', stateName: 'California', population: 51169 },
  { city: 'Harrisonburg', stateId: 'VA', stateName: 'Virginia', population: 51164 },
  { city: 'Troy', stateId: 'NY', stateName: 'New York', population: 51065 },
  { city: 'La Crosse', stateId: 'WI', stateName: 'Wisconsin', population: 51049 },
  { city: 'Mishawaka', stateId: 'IN', stateName: 'Indiana', population: 51020 },
  { city: 'Milford', stateId: 'CT', stateName: 'Connecticut', population: 51004 },
  { city: 'Cuyahoga Falls', stateId: 'OH', stateName: 'Ohio', population: 50979 },
  { city: 'Hoffman Estates', stateId: 'IL', stateName: 'Illinois', population: 50920 },
  { city: 'Clermont', stateId: 'FL', stateName: 'Florida', population: 50851 },
  { city: 'Murray', stateId: 'UT', stateName: 'Utah', population: 50817 },
  { city: 'Fort Pierce', stateId: 'FL', stateName: 'Florida', population: 50805 },
  { city: 'Harrisburg', stateId: 'PA', stateName: 'Pennsylvania', population: 50649 },
  { city: 'Downers Grove', stateId: 'IL', stateName: 'Illinois', population: 50552 },
  { city: 'Enid', stateId: 'OK', stateName: 'Oklahoma', population: 50519 },
  { city: 'Aliso Viejo', stateId: 'CA', stateName: 'California', population: 50457 },
  { city: 'Coral Gables', stateId: 'FL', stateName: 'Florida', population: 50379 },
  { city: 'Goose Creek', stateId: 'SC', stateName: 'South Carolina', population: 50352 },
  { city: 'Cleveland', stateId: 'TN', stateName: 'Tennessee', population: 50232 },
  { city: 'Sherman', stateId: 'TX', stateName: 'Texas', population: 50229 },
  { city: 'Draper', stateId: 'UT', stateName: 'Utah', population: 50166 },
  { city: 'Stillwater', stateId: 'OK', stateName: 'Oklahoma', population: 50138 },
  { city: 'Glendora', stateId: 'CA', stateName: 'California', population: 50101 },
  { city: 'Portage', stateId: 'MI', stateName: 'Michigan', population: 49975 },
  { city: 'St. Louis Park', stateId: 'MN', stateName: 'Minnesota', population: 49899 },
  { city: 'Titusville', stateId: 'FL', stateName: 'Florida', population: 49883 },
  { city: 'Barnstable', stateId: 'MA', stateName: 'Massachusetts', population: 49831 },
  { city: 'Leesburg', stateId: 'VA', stateName: 'Virginia', population: 49831 },
  { city: 'Lawrence', stateId: 'IN', stateName: 'Indiana', population: 49817 },
  { city: 'San Luis Obispo', stateId: 'CA', stateName: 'California', population: 49729 },
  { city: 'Sheboygan', stateId: 'WI', stateName: 'Wisconsin', population: 49624 },
  { city: 'Cedar Hill', stateId: 'TX', stateName: 'Texas', population: 49618 },
  { city: 'Rosemead', stateId: 'CA', stateName: 'California', population: 49582 },
  { city: 'Lakewood', stateId: 'OH', stateName: 'Ohio', population: 49517 },
  { city: 'Huntsville', stateId: 'TX', stateName: 'Texas', population: 49500 },
  { city: 'Chesterfield', stateId: 'MO', stateName: 'Missouri', population: 49465 },
  { city: 'Dublin', stateId: 'OH', stateName: 'Ohio', population: 49456 },
  { city: 'Poway', stateId: 'CA', stateName: 'California', population: 49435 },
  { city: 'Cypress', stateId: 'CA', stateName: 'California', population: 49286 },
  { city: 'Ceres', stateId: 'CA', stateName: 'California', population: 49253 },
  { city: 'Covina', stateId: 'CA', stateName: 'California', population: 49245 },
  { city: 'East Lansing', stateId: 'MI', stateName: 'Michigan', population: 48964 },
  { city: 'Plainfield', stateId: 'IL', stateName: 'Illinois', population: 48881 },
  { city: 'Oro Valley', stateId: 'AZ', stateName: 'Arizona', population: 48855 },
  { city: 'Columbia', stateId: 'TN', stateName: 'Tennessee', population: 48812 },
  { city: 'Wauwatosa', stateId: 'WI', stateName: 'Wisconsin', population: 48794 },
  { city: 'Winter Garden', stateId: 'FL', stateName: 'Florida', population: 48771 },
  { city: 'Bedford', stateId: 'TX', stateName: 'Texas', population: 48728 },
  { city: 'Los Banos', stateId: 'CA', stateName: 'California', population: 48684 },
  { city: 'Holly Springs', stateId: 'NC', stateName: 'North Carolina', population: 48674 },
  { city: 'Wentzville', stateId: 'MO', stateName: 'Missouri', population: 48646 },
  { city: 'Waxahachie', stateId: 'TX', stateName: 'Texas', population: 48617 },
  { city: 'Middletown', stateId: 'CT', stateName: 'Connecticut', population: 48616 },
  { city: 'Wilson', stateId: 'NC', stateName: 'North Carolina', population: 48579 },
  { city: 'Hattiesburg', stateId: 'MS', stateName: 'Mississippi', population: 48522 },
  { city: 'Euclid', stateId: 'OH', stateName: 'Ohio', population: 48421 },
  { city: 'Shakopee', stateId: 'MN', stateName: 'Minnesota', population: 48401 },
  { city: 'Azusa', stateId: 'CA', stateName: 'California', population: 48383 },
  { city: 'Prescott', stateId: 'AZ', stateName: 'Arizona', population: 48224 },
  { city: 'Biloxi', stateId: 'MS', stateName: 'Mississippi', population: 48144 },
  { city: 'Beavercreek', stateId: 'OH', stateName: 'Ohio', population: 48012 },
  { city: 'East Providence', stateId: 'RI', stateName: 'Rhode Island', population: 47961 },
  { city: 'Brea', stateId: 'CA', stateName: 'California', population: 47844 },
  { city: 'Spanish Fork', stateId: 'UT', stateName: 'Utah', population: 47809 },
  { city: 'Urbandale', stateId: 'IA', stateName: 'Iowa', population: 47759 },
  { city: 'Gainesville', stateId: 'GA', stateName: 'Georgia', population: 47712 },
  { city: 'Glenview', stateId: 'IL', stateName: 'Illinois', population: 47634 },
  { city: 'Mansfield', stateId: 'OH', stateName: 'Ohio', population: 47593 },
  { city: 'Niagara Falls', stateId: 'NY', stateName: 'New York', population: 47512 },
  { city: 'Minot', stateId: 'ND', stateName: 'North Dakota', population: 47440 },
  { city: 'Olive Branch', stateId: 'MS', stateName: 'Mississippi', population: 47365 },
  { city: 'Altamonte Springs', stateId: 'FL', stateName: 'Florida', population: 47261 },
  { city: 'Roswell', stateId: 'NM', stateName: 'New Mexico', population: 47176 },
  { city: 'Sayreville', stateId: 'NJ', stateName: 'New Jersey', population: 47165 },
  { city: 'Oakley', stateId: 'CA', stateName: 'California', population: 47158 },
  { city: 'Mentor', stateId: 'OH', stateName: 'Ohio', population: 47113 },
  { city: 'Attleboro', stateId: 'MA', stateName: 'Massachusetts', population: 47085 },
  { city: 'Roseville', stateId: 'MI', stateName: 'Michigan', population: 47047 },
  { city: 'Cerritos', stateId: 'CA', stateName: 'California', population: 46851 },
  { city: 'Binghamton', stateId: 'NY', stateName: 'New York', population: 46773 },
  { city: 'Riverton', stateId: 'UT', stateName: 'Utah', population: 46680 },
  { city: 'Keller', stateId: 'TX', stateName: 'Texas', population: 46643 },
  { city: 'Hackensack', stateId: 'NJ', stateName: 'New Jersey', population: 46630 },
  { city: 'Monroe', stateId: 'LA', stateName: 'Louisiana', population: 46622 },
  { city: 'Delaware', stateId: 'OH', stateName: 'Ohio', population: 46521 },
  { city: 'Charleston', stateId: 'WV', stateName: 'West Virginia', population: 46482 },
  { city: 'Mankato', stateId: 'MN', stateName: 'Minnesota', population: 46459 },
  { city: 'La Mirada', stateId: 'CA', stateName: 'California', population: 46367 },
  { city: 'Rancho Santa Margarita', stateId: 'CA', stateName: 'California', population: 46353 },
  { city: 'West Lafayette', stateId: 'IN', stateName: 'Indiana', population: 46338 },
  { city: 'North Lauderdale', stateId: 'FL', stateName: 'Florida', population: 46335 },
  { city: 'Fuquay-Varina', stateId: 'NC', stateName: 'North Carolina', population: 46317 },
  { city: 'Greer', stateId: 'SC', stateName: 'South Carolina', population: 46316 },
  { city: 'Farmington', stateId: 'NM', stateName: 'New Mexico', population: 46262 },
  { city: 'Newark', stateId: 'CA', stateName: 'California', population: 46254 },
  { city: 'Salina', stateId: 'KS', stateName: 'Kansas', population: 46109 },
  { city: 'Elmhurst', stateId: 'IL', stateName: 'Illinois', population: 46108 },
  { city: 'Morgan Hill', stateId: 'CA', stateName: 'California', population: 45952 },
  { city: 'The Colony', stateId: 'TX', stateName: 'Texas', population: 45897 },
  { city: 'Cutler Bay', stateId: 'FL', stateName: 'Florida', population: 45833 },
  { city: 'Post Falls', stateId: 'ID', stateName: 'Idaho', population: 45800 },
  { city: 'Haltom City', stateId: 'TX', stateName: 'Texas', population: 45786 },
  { city: 'Oakland Park', stateId: 'FL', stateName: 'Florida', population: 45771 },
  { city: 'Strongsville', stateId: 'OH', stateName: 'Ohio', population: 45768 },
  { city: 'Moorhead', stateId: 'MN', stateName: 'Minnesota', population: 45726 },
  { city: 'Salem', stateId: 'MA', stateName: 'Massachusetts', population: 45677 },
  { city: 'Huntington', stateId: 'WV', stateName: 'West Virginia', population: 44942 },
  { city: 'Concord', stateId: 'NH', stateName: 'New Hampshire', population: 44674 },
  { city: 'Burlington', stateId: 'VT', stateName: 'Vermont', population: 44432 },
  { city: 'Covington', stateId: 'KY', stateName: 'Kentucky', population: 41611 },
  { city: 'West Fargo', stateId: 'ND', stateName: 'North Dakota', population: 41027 },
  { city: 'Dover', stateId: 'DE', stateName: 'Delaware', population: 40191 },
  { city: 'Lewiston', stateId: 'ME', stateName: 'Maine', population: 38772 },
  { city: 'Butte', stateId: 'MT', stateName: 'Montana', population: 35480 },
  { city: 'Kearney', stateId: 'NE', stateName: 'Nebraska', population: 34741 },
  { city: 'Dover', stateId: 'NH', stateName: 'New Hampshire', population: 33909 },
  { city: 'Gillette', stateId: 'WY', stateName: 'Wyoming', population: 33846 },
  { city: 'Rochester', stateId: 'NH', stateName: 'New Hampshire', population: 33598 },
  { city: 'Laramie', stateId: 'WY', stateName: 'Wyoming', population: 32957 },
  { city: 'Bangor', stateId: 'ME', stateName: 'Maine', population: 32446 },
  { city: 'Fairbanks', stateId: 'AK', stateName: 'Alaska', population: 31732 },
  { city: 'Juneau', stateId: 'AK', stateName: 'Alaska', population: 31572 },
  { city: 'Newark', stateId: 'DE', stateName: 'Delaware', population: 30506 },
  { city: 'Morgantown', stateId: 'WV', stateName: 'West Virginia', population: 30490 },
  { city: 'Parkersburg', stateId: 'WV', stateName: 'West Virginia', population: 28834 },
  { city: 'Aberdeen', stateId: 'SD', stateName: 'South Dakota', population: 27919 },
  { city: 'South Portland', stateId: 'ME', stateName: 'Maine', population: 26994 },
  { city: 'Wheeling', stateId: 'WV', stateName: 'West Virginia', population: 26060 },
  { city: 'Middletown', stateId: 'DE', stateName: 'Delaware', population: 25686 },
  { city: 'Auburn', stateId: 'ME', stateName: 'Maine', population: 25200 },
  { city: 'Brookings', stateId: 'SD', stateName: 'South Dakota', population: 24555 },
  { city: 'Watertown', stateId: 'SD', stateName: 'South Dakota', population: 23492 },
  { city: 'Rock Springs', stateId: 'WY', stateName: 'Wyoming', population: 22967 },
  { city: 'South Burlington', stateId: 'VT', stateName: 'Vermont', population: 21713 },
  { city: 'Rutland', stateId: 'VT', stateName: 'Vermont', population: 15565 },
  { city: 'Milford', stateId: 'DE', stateName: 'Delaware', population: 14079 },
  { city: 'Essex Junction', stateId: 'VT', stateName: 'Vermont', population: 10787 },
  { city: 'Wasilla', stateId: 'AK', stateName: 'Alaska', population: 10318 },
  { city: 'Winooski', stateId: 'VT', stateName: 'Vermont', population: 8370 },
  { city: 'Sitka', stateId: 'AK', stateName: 'Alaska', population: 8355 },
]
